name: CI
on:
  pull_request:
  push:
    branches: [main]
#
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage --exclude-tags golden
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: app/coverage/lcov.info
      - name: Test du secret
        run: echo "Le secret vaut ${{ secrets.MON_SECRET }}"

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/app/outputs/flutter-apk/app-release.apk

      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SA }}
          groups: testeurs
          file: app/build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Build automatique du commit ${{ github.sha }}"